version: '3.4'

services:
  leitura:
    image: leitura
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
